server:
  port: 9191

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: person-service
          uri: lb://PERSON-SERVICE
          predicates:
            - Path=/people/**

        - id: dante-service
          uri: lb://DANTE-SERVICE
          predicates:
            - Path=/dante/**
          filters:
            - AuthFilter

        - id: jwt-server
          uri: lb://jwt-server
          predicates:
            - Path=/auth
  zipkin: 
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
